---
- name: Test playbook for zilux.satellite
  hosts: "{{ env | localhost }}"
  # hosts: "{{ env | default(omit) }}"
  gather_facts: false
  become: false
  vars_files:
    - vars/common.yml
    - vars/secrets.yml
    - vars/{{ env.split('_') | last }}.yml

  tasks:

    - name: Block to do all with localhost
      delegate_to: localhost
      block:

        - name: Show env
          ansible.builtin.debug:
            msg:
              - "Environment: {{ env | default('not_set') }}"
              - "Secret: {{ secret | default('not_set') }}"
              - "Common: {{ common | default('not_set') }}"
              - "Locations: {{ locations | default('not_set') }}"
              - "Capsules: {{ capsules  | default('not_set') }}"

        - name: Run role from zilux.satellite
          ansible.builtin.import_role:
            name: zilux.satellite.dummy_role
          when: env in ['prod', 'pa'] 
