---
- name: Test playbook for zilux.satellite
  hosts: "{{ env | default(omit) }}"
  gather_facts: false
  become: false
  vars_files:
    - vars/common.yml
    - vars/{{ env.split('_') | last }}.yml
    - vars/{{ env.split('_') | last }}_secrets.yml

  tasks:

    - name: Block to do all with localhost
      delegate_to: localhost
      block:

        - name: Show env
          ansible.builtin.debug:
            msg:
              - 'Environment: {{ env }}'
              - 'Secret: {{ secret }}'
              - 'Common: {{ common }}'
              - 'Locations: {{ locations }}'
              - 'Capsules: {{ capsules }}'

        - name: Run role from zilux.satellite
          ansible.builtin.import_role:
            name: zilux.satellite.dummy_role
          when: env == 'prod'
